services:
  ovpn:
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
        - ./${OPENVPN_FILE}:/config/config.ovpn
    environment:
        - LOCAL_NETWORK=10.0.8.1/24
        - OPENVPN_USERNAME=${OPENVPN_USERNAME}
        - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    ports:
        - 8082:80
        - 8081:8080
    restart: always
